version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - yamdb_final_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: martyshovss/api_yamdb:latest
    restart: always
    volumes:
      - yamdb_final_static:/app/static/
      - yamdb_final_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - yamdb_final_static:/var/html/static/
      - yamdb_final_media:/var/html/media/
    depends_on:
      - web

volumes:
  yamdb_final_static:
  yamdb_final_media:
  yamdb_final_db:
